$base_path = ~/.config/hypr
source = $base_path/monitors.conf
source = $base_path/programs.conf
source = $base_path/autostart.conf
source = $base_path/environt.conf
source = $base_path/window-border.conf
source = $base_path/decoration.conf
source = $base_path/animations.conf
source = $base_path/input.conf
source = $base_path/gestures.conf
source = $base_path/keybindings.conf
source = $base_path/windowrules.conf

# master {
#   new_status = master
# }

dwindle {
    preserve_split = true         # Keep split orientation fixed
    smart_split = false           # Optional: enable for cursor-based splits
    smart_resizing = true         # Easier window resizing
    default_split_ratio = 1.0     # Even split by default
    split_width_multiplier = 1.0  # Adjust for widescreens if needed
    use_active_for_splits = true  # Prefer active window for split
}

misc {
  force_default_wallpaper = -1 # Set to 0 or 1 to disable the anime mascot wallpapers
  disable_hyprland_logo = false # If true disables the random hyprland logo / anime girl background. 
}

device {
  name = epic-mouse-v1
  sensitivity = -0.5
}

