# Or execute your favorite apps at launch like this:

exec-once = ibus-daemon -drx
exec-once = waybar
exec-once = hypridle
exec-once = copyq
exec-once = swaync
exec-once = wl-paste --watch cliphist store &
# exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = nm-applet
exec-once=iwgtk -i
exec-once = blueman-applet
exec-once = kdeconnect-indicator
exec-once = swww-daemon --format xrgb
exec-once = waypaper --restore
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store

#apps i want to be auto started
exec-once = discord
# exec-once = $HOME/my-env/hypr/scripts/livewallpaper.sh
