env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = GTK_IM_MODULE,ibus
env = QT_IM_MODULE,ibus
env = XMODIFIERS,@im=ibus
env = INPUT_METHOD,ibus
env = SDL_IM_MODULE,ibus

env = XCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_THEME,Bibata-Modern-Ice

