# ==================================================
# Hyprland New Gesture Syntax — Smooth & Natural
# ==================================================

# 3-Finger Horizontal: The "Classic" Workspace Swipe
gesture = 3, horizontal, workspace

# 3-Finger up: Makes the app Full screen
gesture = 3, up, fullscreen
