# Change the default Omarchy look'n'feel

$anim_enable = 1
$anim_base = 6.0
$anim_fast = 4.5
$anim_slow = 8.0
# https://wiki.hypr.land/Configuring/Basics/Variables/#general

general {
    # No gaps between windows or borders
    gaps_in = 1
    gaps_out = 5
    border_size = 1

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 2

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    enabled = $anim_enable

    bezier = appleDefault, 0.25, 1, 0.5, 1
    bezier = appleSnap, 0.4, 0, 0.2, 1
    bezier = appleWorkspace, 0.33, 1, 0.68, 1

    animation = windows, 1, $anim_base, appleDefault
    animation = windowsIn, 1, $anim_base, appleDefault, popin 90%
    animation = windowsOut, 1, $anim_fast, appleSnap, popin 95%

    animation = fadeIn, 1, $anim_fast, appleDefault
    animation = fadeOut, 1, $anim_fast, appleDefault

    animation = layers, 1, $anim_base, appleDefault, slide
    animation = layersIn, 1, $anim_fast, appleDefault, slide
    animation = layersOut, 1, $anim_slow, appleSnap, slide

    animation = workspaces, 1, $anim_base, appleWorkspace, slide
}

# https://wiki.hypr.land/Configuring/Basics/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/
scrolling {
    # See only one column per screen instead of two
    # column_width = 0.97
}
