windowrule {
    name = bangla-keyboard-compact
    match:class = ibus-ui-gtk3
    
    # Force floating and prevent it from stealing focus
    float = on
    no_initial_focus = on
    
    # Resize the window to be smaller (Width Height)
    size = 300 100
    
    # Position it exactly at the cursor
    # (cursor_y+25) pushes it slightly below the pointer so it doesn't block it
    move = (cursor_x) (cursor_y+25)
    
    # Clean up the look
    no_anim = on
    border_size = 1
}
