# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
exec-once = waybar
exec-once = hyprpaper
exec-once = copyq
exec-once = ibus-daemon -drx
exec-once = swaync
exec-once = wl-paste --watch cliphist store &
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = nm-applet
exec-once = blueman-applet
