general {
    gaps_in = 5
    gaps_out = 5

    border_size = 1

    col.active_border = rgba(196,167,231,0.8) rgba(203,166,247,0.6) 45deg
    col.inactive_border = rgba(110,106,134,0.5)

    resize_on_border = false
    allow_tearing = false

    layout = master
}
