# -----------------------------------------------------
# Window rules
# -----------------------------------------------------

windowrule = tile, title:^(Microsoft-edge)$
windowrule = tile, title:^(Brave-browser)$
windowrule = tile, title:^(Chromium)$
windowrule = float, title:^(pavucontrol)$
windowrule = float, title:^(blueman-manager)$
windowrule = float, title:^(nm-connection-editor)$
windowrule = float, title:^(qalculate-gtk)$

# Browser Picture in Picture
windowrule = float, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$
windowrule = move 69.5% 4%, title:^(Picture-in-Picture)$

# idleinhibit
windowrule = idleinhibit fullscreen,class:([window]) # Available modes: n


# Float the Avro suggestion popup
windowrule = float, class:^(ibus-ui-gtk3)$
windowrule = noinitialfocus, class:^(ibus-ui-gtk3)$
windowrule = noborder, class:^(ibus-ui-gtk3)$

# Smaller suggestion popup + move above input box
windowrulev2 = size 320 60, class:^(ibus-ui-gtk3)$
windowrulev2 = move 45% 75%, class:^(ibus-ui-gtk3)$
# windowrulev2 = opacity 0.92, class:^(ibus-ui-gtk3)$

windowrule = float, title:^(Open File)$
windowrule = float, title:^(Save File)$
windowrule = float, title:^(Preferences)$

windowrule = float, title:^(.*DevTools.*)$
windowrule = float, title:^(.*Preferences.*)$
windowrule = float, title:^(.*Settings.*)$

windowrule = float, title:^(lazygit)$
windowrule = noborder, title:^(lazygit)$

windowrule = float, title:^(.*Meet.*)$
windowrule = float, title:^(.*Zoom.*)$
windowrule = float, title:^(.*Webcam.*)$

windowrule = float, class:^(Dunst)$
windowrule = pin, class:^(Dunst)$

windowrule = tile, class:^(code-url-handler)$
windowrule = tile, class:^(Code)$
windowrule = tile, class:^(org.gnome.gedit)$

windowrule = tile, class:^(Google-chrome)$
windowrule = float, title:^(About .*)$
windowrule = float, title:^(.*Popup.*)$
windowrule = float, title:^(.*Context.*)$
