# REMOVE OMARCHY DEFAULT CONFLICTS
# =========================================================

# unbind = SUPER, RETURN
unbind = SUPER, E
unbind = SUPER, B

unbind = SUPER, Q
unbind = SUPER SHIFT, Q

unbind = SUPER, F
unbind = SUPER, M
unbind = SUPER, T
unbind = SUPER SHIFT, T

unbind = SUPER, H
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L

unbind = SUPER SHIFT, H
unbind = SUPER SHIFT, J
unbind = SUPER SHIFT, K
unbind = SUPER SHIFT, L

unbind = SUPER ALT, H
unbind = SUPER ALT, J
unbind = SUPER ALT, K
unbind = SUPER ALT, L

unbind = SUPER, TAB
unbind = SUPER SHIFT, TAB

unbind = SUPER, G

unbind = SUPER, PRINT

unbind = SUPER, V
unbind = ALT, R

unbind = SUPER SHIFT, X
unbind = SUPER, X

unbind = SUPER, LEFT
unbind = SUPER, RIGHT
unbind = SUPER, UP
unbind = SUPER, DOWN

unbind = SUPER, 1
unbind = SUPER, 2
unbind = SUPER, 3
unbind = SUPER, 4
unbind = SUPER, 5
unbind = SUPER, 6
unbind = SUPER, 7
unbind = SUPER, 8
unbind = SUPER, 9
unbind = SUPER, 0

unbind = SUPER SHIFT, 1
unbind = SUPER SHIFT, 2
unbind = SUPER SHIFT, 3
unbind = SUPER SHIFT, 4
unbind = SUPER SHIFT, 5
unbind = SUPER SHIFT, 6
unbind = SUPER SHIFT, 7
unbind = SUPER SHIFT, 8
unbind = SUPER SHIFT, 9
unbind = SUPER SHIFT, 0

unbind = SUPER, Y
unbind = SUPER SHIFT, Y

# unbind = SUPER, S
# unbind = SUPER SHIFT, S

